# Generated by Django 4.0.5 on 2022-06-10 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pub_author_admin',
            field=models.CharField(default=1, max_length=1000, verbose_name='Автор публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='pub_time_admin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
