# Generated by Django 4.0.5 on 2022-06-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_document_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(upload_to='main/docs/', verbose_name='Изображение'),
        ),
    ]
