# Generated by Django 4.0.5 on 2022-06-07 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(default=1, max_length=4, verbose_name='Год издания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор/издатель'),
        ),
    ]
