# Generated by Django 4.0.5 on 2022-06-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_document_author_user_document_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(height_field=947, upload_to='images/', verbose_name='Изображение', width_field=718),
        ),
    ]
