# Generated by Django 4.0.5 on 2022-06-08 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_remove_document_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Лайки', to=settings.AUTH_USER_MODEL),
        ),
    ]
