# Generated by Django 4.0.5 on 2022-06-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_document_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='likes',
        ),
    ]
