# Generated by Django 4.0.5 on 2022-06-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_document_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=1000, verbose_name='Автор/издатель'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
